# Generated by Django 3.2.19 on 2023-07-30 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_weather_weather_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'verbose_name': 'Ob-havo', 'verbose_name_plural': 'Ob-havo'},
        ),
        migrations.AddField(
            model_name='weather',
            name='image',
            field=models.ImageField(default=0, upload_to='image_test', verbose_name='Viloyat rasmi: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weather',
            name='reg_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
