# Generated by Django 3.2.19 on 2023-07-31 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230730_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Viloyat rasmi: '),
        ),
    ]
