# Generated by Django 3.2.19 on 2023-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_weather_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Viloyat rasmi: '),
        ),
    ]
