# Generated by Django 3.2.19 on 2023-07-31 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_weather_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='image',
            field=models.ImageField(upload_to='image_test', verbose_name='Viloyat rasmi: '),
        ),
    ]
